# .gitlab-ci.yml

# Define the cache settings for the pipeline
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .venv/
    - ~/.cache/pip/

# Define the stages that the pipeline will go through
stages:
  - build
  - test
  - deploy

# Define the jobs that will run in each stage
build:
  stage: build
  image: python:3.8
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - __init__.py
      - app.py

test:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest tests/
  artifacts:
    paths:
      - tests/
    when: always

deploy:
  stage: deploy
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - pip install awscli
    - aws s3 cp app.py s3://<your-bucket-name>/app.py
  when: manual
  only:
    - main
